builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  disable: true
brews:
  -
    tap:
      owner: chebread
      name: battime
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

    homepage: "https://github.com/chebread/battime"
    description: "Check the battery usage time."
    license: "MIT"

    install: |
      bin.install "battime"